title: うさTVニュース
description: "毎日のトップページをアーカイブ"
url: "https://mofu.rabbitflowerdiary.com"  # ドメイン直下のトップ
baseurl: "/archive-site"                     # アーカイブ専用ディレクトリ

# Jekyllのビルド設定
sass:
  style: compressed

# プラグインは使用しない（自作レイアウトを優先）
plugins: []

# タイムゾーン
timezone: Asia/Tokyo

# Markdown / Excerpt の設定（抜粋を自動生成できるように）
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
