title: うさTVニュース
description:  archive
baseurl: "/archive-site/assets"
url: "https://mofu.rabbitflowerdiary.com"

# Jekyllのビルド設定
sass:
  style: compressed

# テーマは使わず自作レイアウトを優先
plugins: []

timezone: Asia/Tokyo
