title: "うさTVニュース"
description: "毎日のトップページをアーカイブ"
url: "https://mofu.rabbitflowerdiary.com"   # ドメイン直下のトップ
baseurl: "/archive-site"                     # アーカイブ専用ディレクトリ

# Jekyllのビルド設定
sass:
  style: compressed

# プラグインは使用しない（自作レイアウトを優先）
plugins: []

# タイムゾーン
timezone: Asia/Tokyo

# Markdown / Excerpt の設定
markdown: kramdown
kramdown:
  input: GFM

# 抜粋の区切り（archive.htmlで {{ post.excerpt }} を使うとここまで表示される）
excerpt_separator: "<!-- more -->"


- name: Extract excerpt block
  run: |
    sed -n '/<!-- excerpt:start -->/,/<!-- excerpt:end -->/p' top.html \
      | sed '1d;$d' > archive/$(date +'%Y-%m-%d')-top-page.html
