name: Auto Archive Top Page

on:
  schedule:
    - cron: '0 16 * * *'  # 毎日0時に実行（日本時間の午前1時）
  workflow_dispatch:      # 手動トリガーも可能

permissions:
  contents: write

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      # リポジトリをチェックアウト
      - uses: actions/checkout@v4

      # 今日の日付を取得
      - name: Set Date
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      # トップページをコピーして _posts に Markdown ファイルを作成
      - name: Create Archive Markdown
        run: |
          mkdir -p _posts
          cat <<EOT > _posts/${DATE}-top-page.md
---
layout: post
title: "${DATE} トップページ"
date: ${DATE}
---

{% raw %}
{% include_relative ../index.html %}
{% endraw %}
EOT

      # 変更をコミットしてプッシュ
      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add _posts/${DATE}-top-page.md
          git commit -m "Auto archive ${DATE}" || echo "No changes to commit"
          git push
